name: esdap
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.8
  - joblib=0.14.1
  - matplotlib=3.1.2
  - mlflow=1.5.0
  - mne=0.19.2
  - numba=0.46.0
  - numpy=1.18.0
  - pandas=1.0.0
  - pywavelets=1.1.1
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - tensorflow=2.0.0
  - xgboost=0.90
