python -m esdap.training.train_tensorflow --run_name="FCN_pre30-post30_binary_chb13_30-15_allfeatures" --data_path="../data/chb-mit/30-15" --patient_name="chb13" --labels_filename="labels-pre30-post30" --classifier_name="FCN" --binary_classification="True" --n_splits=3 --random_seed="False" --epochs=30 --ft_moments="True" --ft_peak_to_peak="True" --ft_max_correlation="True" --ft_absolute_area="True" --ft_decorrelation_time="True" --ft_dwt_coeffs="True" --ft_psd_ratio="True" --ft_splv="True"

python -m esdap.training.train_tensorflow --run_name="LSTM_pre30-post30_binary_chb13_30-15_allfeatures" --data_path="../data/chb-mit/30-15" --patient_name="chb13" --labels_filename="labels-pre30-post30" --classifier_name="LSTM" --binary_classification="True" --timesteps=10 --n_splits=3 --random_seed="False" --epochs=30 --ft_moments="True" --ft_peak_to_peak="True" --ft_max_correlation="True" --ft_absolute_area="True" --ft_decorrelation_time="True" --ft_dwt_coeffs="True" --ft_psd_ratio="True" --ft_splv="True"

python -m esdap.training.train_tensorflow --run_name="CNN_pre30-post30_binary_chb13_30-15_allfeatures" --data_path="../data/chb-mit/30-15" --patient_name="chb13" --labels_filename="labels-pre30-post30" --classifier_name="CNN" --binary_classification="True" --timesteps=10 --n_splits=3 --random_seed="False" --epochs=30 --ft_moments="True" --ft_peak_to_peak="True" --ft_max_correlation="True" --ft_absolute_area="True" --ft_decorrelation_time="True" --ft_dwt_coeffs="True" --ft_psd_ratio="True" --ft_splv="True"



python -m esdap.training.train_tensorflow --run_name="LSTM_pre5-post5_binary_chb13_30-15_allfeatures" --data_path="../data/chb-mit/30-15" --patient_name="chb13" --labels_filename="labels-pre5-post5" --classifier_name="LSTM" --binary_classification="True" --timesteps=10 --n_splits=3 --random_seed="False" --epochs=30 --ft_moments="True" --ft_peak_to_peak="True" --ft_max_correlation="True" --ft_absolute_area="True" --ft_decorrelation_time="True" --ft_dwt_coeffs="True" --ft_psd_ratio="True" --ft_splv="True"

python -m esdap.training.train_tensorflow --run_name="LSTM_pre10-post10_binary_chb13_30-15_allfeatures" --data_path="../data/chb-mit/30-15" --patient_name="chb13" --labels_filename="labels-pre10-post10" --classifier_name="LSTM" --binary_classification="True" --timesteps=10 --n_splits=3 --random_seed="False" --epochs=30 --ft_moments="True" --ft_peak_to_peak="True" --ft_max_correlation="True" --ft_absolute_area="True" --ft_decorrelation_time="True" --ft_dwt_coeffs="True" --ft_psd_ratio="True" --ft_splv="True"

python -m esdap.training.train_tensorflow --run_name="LSTM_pre15-post15_binary_chb13_30-15_allfeatures" --data_path="../data/chb-mit/30-15" --patient_name="chb13" --labels_filename="labels-pre15-post15" --classifier_name="LSTM" --binary_classification="True" --timesteps=10 --n_splits=3 --random_seed="False" --epochs=30 --ft_moments="True" --ft_peak_to_peak="True" --ft_max_correlation="True" --ft_absolute_area="True" --ft_decorrelation_time="True" --ft_dwt_coeffs="True" --ft_psd_ratio="True" --ft_splv="True"

python -m esdap.training.train_tensorflow --run_name="LSTM_pre20-post20_binary_chb13_30-15_allfeatures" --data_path="../data/chb-mit/30-15" --patient_name="chb13" --labels_filename="labels-pre20-post20" --classifier_name="LSTM" --binary_classification="True" --timesteps=10 --n_splits=3 --random_seed="False" --epochs=30 --ft_moments="True" --ft_peak_to_peak="True" --ft_max_correlation="True" --ft_absolute_area="True" --ft_decorrelation_time="True" --ft_dwt_coeffs="True" --ft_psd_ratio="True" --ft_splv="True"

python -m esdap.training.train_tensorflow --run_name="LSTM_pre25-post25_binary_chb13_30-15_allfeatures" --data_path="../data/chb-mit/30-15" --patient_name="chb13" --labels_filename="labels-pre25-post25" --classifier_name="LSTM" --binary_classification="True" --timesteps=10 --n_splits=3 --random_seed="False" --epochs=30 --ft_moments="True" --ft_peak_to_peak="True" --ft_max_correlation="True" --ft_absolute_area="True" --ft_decorrelation_time="True" --ft_dwt_coeffs="True" --ft_psd_ratio="True" --ft_splv="True"

python -m esdap.training.train_tensorflow --run_name="LSTM_pre30-post30_binary_chb13_30-15_allfeatures" --data_path="../data/chb-mit/30-15" --patient_name="chb13" --labels_filename="labels-pre30-post30" --classifier_name="LSTM" --binary_classification="True" --timesteps=10 --n_splits=3 --random_seed="False" --epochs=30 --ft_moments="True" --ft_peak_to_peak="True" --ft_max_correlation="True" --ft_absolute_area="True" --ft_decorrelation_time="True" --ft_dwt_coeffs="True" --ft_psd_ratio="True" --ft_splv="True"

python -m esdap.training.train_tensorflow --run_name="LSTM_pre60-post60_binary_chb13_30-15_allfeatures" --data_path="../data/chb-mit/30-15" --patient_name="chb13" --labels_filename="labels-pre60-post60" --classifier_name="LSTM" --binary_classification="True" --timesteps=10 --n_splits=3 --random_seed="False" --epochs=30 --ft_moments="True" --ft_peak_to_peak="True" --ft_max_correlation="True" --ft_absolute_area="True" --ft_decorrelation_time="True" --ft_dwt_coeffs="True" --ft_psd_ratio="True" --ft_splv="True"



python -m esdap.training.train_tensorflow --run_name="FCN_pre30-post30_binary_chb16_30-15_TDfeatures" --data_path="../data/chb-mit/30-15" --patient_name="chb16" --labels_filename="labels-pre30-post30" --classifier_name="FCN" --binary_classification="True" --timesteps=10 --n_splits=3 --random_seed="False" --epochs=30 --ft_moments="True" --ft_peak_to_peak="True" --ft_max_correlation="False" --ft_absolute_area="True" --ft_decorrelation_time="True" --ft_dwt_coeffs="False" --ft_psd_ratio="False" --ft_splv="False"

python -m esdap.training.train_tensorflow --run_name="FCN_pre30-post30_binary_chb16_30-15_FDfeatures" --data_path="../data/chb-mit/30-15" --patient_name="chb16" --labels_filename="labels-pre30-post30" --classifier_name="FCN" --binary_classification="True" --timesteps=10 --n_splits=3 --random_seed="False" --epochs=30 --ft_moments="False" --ft_peak_to_peak="False" --ft_max_correlation="False" --ft_absolute_area="False" --ft_decorrelation_time="False" --ft_dwt_coeffs="True" --ft_psd_ratio="True" --ft_splv="False"

python -m esdap.training.train_tensorflow --run_name="FCN_pre30-post30_binary_chb16_30-15_Bifeatures" --data_path="../data/chb-mit/30-15" --patient_name="chb16" --labels_filename="labels-pre30-post30" --classifier_name="FCN" --binary_classification="True" --timesteps=10 --n_splits=3 --random_seed="False" --epochs=30 --ft_moments="False" --ft_peak_to_peak="False" --ft_max_correlation="True" --ft_absolute_area="False" --ft_decorrelation_time="False" --ft_dwt_coeffs="False" --ft_psd_ratio="False" --ft_splv="True"

python -m esdap.training.train_tensorflow --run_name="LSTM_pre30-post30_binary_chb16_30-15_TDfeatures" --data_path="../data/chb-mit/30-15" --patient_name="chb16" --labels_filename="labels-pre30-post30" --classifier_name="LSTM" --binary_classification="True" --timesteps=10 --n_splits=3 --random_seed="False" --epochs=30 --ft_moments="True" --ft_peak_to_peak="True" --ft_max_correlation="False" --ft_absolute_area="True" --ft_decorrelation_time="True" --ft_dwt_coeffs="False" --ft_psd_ratio="False" --ft_splv="False"

python -m esdap.training.train_tensorflow --run_name="LSTM_pre30-post30_binary_chb16_30-15_FDfeatures" --data_path="../data/chb-mit/30-15" --patient_name="chb16" --labels_filename="labels-pre30-post30" --classifier_name="LSTM" --binary_classification="True" --timesteps=10 --n_splits=3 --random_seed="False" --epochs=30 --ft_moments="False" --ft_peak_to_peak="False" --ft_max_correlation="False" --ft_absolute_area="False" --ft_decorrelation_time="False" --ft_dwt_coeffs="True" --ft_psd_ratio="True" --ft_splv="False"

python -m esdap.training.train_tensorflow --run_name="LSTM_pre30-post30_binary_chb16_30-15_Bifeatures" --data_path="../data/chb-mit/30-15" --patient_name="chb16" --labels_filename="labels-pre30-post30" --classifier_name="LSTM" --binary_classification="True" --timesteps=10 --n_splits=3 --random_seed="False" --epochs=30 --ft_moments="False" --ft_peak_to_peak="False" --ft_max_correlation="True" --ft_absolute_area="False" --ft_decorrelation_time="False" --ft_dwt_coeffs="False" --ft_psd_ratio="False" --ft_splv="True"

python -m esdap.training.train_tensorflow --run_name="CNN_pre30-post30_binary_chb16_30-15_TDfeatures" --data_path="../data/chb-mit/30-15" --patient_name="chb16" --labels_filename="labels-pre30-post30" --classifier_name="CNN" --binary_classification="True" --timesteps=10 --n_splits=3 --random_seed="False" --epochs=30 --ft_moments="True" --ft_peak_to_peak="True" --ft_max_correlation="False" --ft_absolute_area="True" --ft_decorrelation_time="True" --ft_dwt_coeffs="False" --ft_psd_ratio="False" --ft_splv="False"

python -m esdap.training.train_tensorflow --run_name="CNN_pre30-post30_binary_chb16_30-15_FDfeatures" --data_path="../data/chb-mit/30-15" --patient_name="chb16" --labels_filename="labels-pre30-post30" --classifier_name="CNN" --binary_classification="True" --timesteps=10 --n_splits=3 --random_seed="False" --epochs=30 --ft_moments="False" --ft_peak_to_peak="False" --ft_max_correlation="False" --ft_absolute_area="False" --ft_decorrelation_time="False" --ft_dwt_coeffs="True" --ft_psd_ratio="True" --ft_splv="False"

python -m esdap.training.train_tensorflow --run_name="CNN_pre30-post30_binary_chb16_30-15_Bifeatures" --data_path="../data/chb-mit/30-15" --patient_name="chb16" --labels_filename="labels-pre30-post30" --classifier_name="CNN" --binary_classification="True" --timesteps=10 --n_splits=3 --random_seed="False" --epochs=30 --ft_moments="False" --ft_peak_to_peak="False" --ft_max_correlation="True" --ft_absolute_area="False" --ft_decorrelation_time="False" --ft_dwt_coeffs="False" --ft_psd_ratio="False" --ft_splv="True"

